apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - postgres.yaml
  - irsa-serviceaccount.yaml

commonLabels:
  app: q-profile-vending
  version: v1.0.0
