apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      version: v1.0.0
  template:
    metadata:
      labels:
        app: postgres
        version: v1.0.0
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: qprofiles
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
    version: v1.0.0
spec:
  selector:
    app: postgres
    version: v1.0.0
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
