name: Build and Deploy

on:
  push:
    branches: [master]
    paths: ['app/**']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      run: |
        docker build -t mtrampic/q-profile-vending:latest ./app
        docker tag mtrampic/q-profile-vending:latest mtrampic/q-profile-vending:${{ github.sha }}
        
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u mtrampic --password-stdin
        
        docker push mtrampic/q-profile-vending:latest
        docker push mtrampic/q-profile-vending:${{ github.sha }}
    
    - name: Update deployment image
      run: |
        sed -i 's|mtrampic/q-profile-vending:.*|mtrampic/q-profile-vending:${{ github.sha }}|' k8s/deployment.yaml
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add k8s/deployment.yaml
        git commit -m "Update image to ${{ github.sha }}" || exit 0
        git push
