name: Build and Deploy

on:
  push:
    branches: [master]
    paths: ['app/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: mtrampic
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./app
        platforms: linux/arm64
        push: true
        tags: |
          mtrampic/q-profile-vending:latest
          mtrampic/q-profile-vending:${{ github.sha }}
