name: Build and Deploy

on:
  push:
    branches: [master]
    paths: ['app/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: mtrampic
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./app
        platforms: linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          mtrampic/q-profile-vending:latest
          mtrampic/q-profile-vending:${{ github.sha }}
    
    - name: Update deployment image
      run: |
        sed -i 's|mtrampic/q-profile-vending:.*|mtrampic/q-profile-vending:${{ github.sha }}|' k8s/deployment.yaml
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add k8s/deployment.yaml
        git commit -m "Update image to ${{ github.sha }}" || exit 0
        git push
